
clone:
		sudo virt-clone --original debian11 --name debian11-1 --auto-clone



clone:
		sudo virt-clone --print-xml --debug --original debian11 --name debian11-1 --auto-clone 



clone:
		sudo virt-clone --original vm1 --name vm3 --file /home/mohsen/virtspace/storages/mint-vm3.qcow2 



clone:
		sudo virt-clone --debug --original vm1 --name vm3 --file /home/mohsen/virtspace/storages/mint-vm3.qcow2 



clone:
		sudo virt-clone --print-xml --debug --original vm1 --name vm3 --file /home/mohsen/virtspace/storages/mint-vm3.qcow2 




delete a vm:
		sudo virsh undefine vmName

or 
		sudo virsh --domain vmName



gui:

	sudo virsh start vm3
	
	sudo virt-viewer vm3



